[ 2024-11-25 20:35:46,912 ] 22 root - INFO - Data Ingestion has been started
[ 2024-11-25 20:35:46,912 ] 24 root - INFO - Data reading using Pandas from local file system
[ 2024-11-25 20:35:46,914 ] 42 root - INFO - Error occured in data ingestion stage
[ 2024-11-25 20:35:46,915 ] 51 root - ERROR - 
Error occurred in Python script:
→ File: /home/fahad/mlops/model-training-with-modular-workflow/src/components/data_ingestion.py
→ Line number: 25
→ Error message: [Errno 2] No such file or directory: 'data-source/cleaned_data.csv'
